package corbaBanque;


/**
* corbaBanque/IBanqueRemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* dimanche 9 novembre 2025 21 h 38 CET
*/


// Interface pour les opérations bancaires
public interface IBanqueRemoteOperations 
{

  // Creer un nouveau compte
  void creerCompte (corbaBanque.Compte cpte);

  // Effectuer un verser
  void verser (float mt, int code);

  // Effectuer un retrait
  void retrait (float mt, int code);

  // Obtenir un compte par son code
  corbaBanque.Compte getCompte (int code);

  // Obtenir tous les comptes
  corbaBanque.Compte[] getComptes ();

  // Conversion de montant
  double conversion (float mt);
} // interface IBanqueRemoteOperations
