package corbaBanque;


/**
* corbaBanque/IBanqueRemotePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* dimanche 9 novembre 2025 21 h 38 CET
*/


// Interface pour les opérations bancaires
public abstract class IBanqueRemotePOA extends org.omg.PortableServer.Servant
 implements corbaBanque.IBanqueRemoteOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("creerCompte", new java.lang.Integer (0));
    _methods.put ("verser", new java.lang.Integer (1));
    _methods.put ("retrait", new java.lang.Integer (2));
    _methods.put ("getCompte", new java.lang.Integer (3));
    _methods.put ("getComptes", new java.lang.Integer (4));
    _methods.put ("conversion", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // Creer un nouveau compte
       case 0:  // corbaBanque/IBanqueRemote/creerCompte
       {
         corbaBanque.Compte cpte = corbaBanque.CompteHelper.read (in);
         this.creerCompte (cpte);
         out = $rh.createReply();
         break;
       }


  // Effectuer un verser
       case 1:  // corbaBanque/IBanqueRemote/verser
       {
         float mt = in.read_float ();
         int code = in.read_long ();
         this.verser (mt, code);
         out = $rh.createReply();
         break;
       }


  // Effectuer un retrait
       case 2:  // corbaBanque/IBanqueRemote/retrait
       {
         float mt = in.read_float ();
         int code = in.read_long ();
         this.retrait (mt, code);
         out = $rh.createReply();
         break;
       }


  // Obtenir un compte par son code
       case 3:  // corbaBanque/IBanqueRemote/getCompte
       {
         int code = in.read_long ();
         corbaBanque.Compte $result = null;
         $result = this.getCompte (code);
         out = $rh.createReply();
         corbaBanque.CompteHelper.write (out, $result);
         break;
       }


  // Obtenir tous les comptes
       case 4:  // corbaBanque/IBanqueRemote/getComptes
       {
         corbaBanque.Compte $result[] = null;
         $result = this.getComptes ();
         out = $rh.createReply();
         corbaBanque.tabComptesHelper.write (out, $result);
         break;
       }


  // Conversion de montant
       case 5:  // corbaBanque/IBanqueRemote/conversion
       {
         float mt = in.read_float ();
         double $result = (double)0;
         $result = this.conversion (mt);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:corbaBanque/IBanqueRemote:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public IBanqueRemote _this() 
  {
    return IBanqueRemoteHelper.narrow(
    super._this_object());
  }

  public IBanqueRemote _this(org.omg.CORBA.ORB orb) 
  {
    return IBanqueRemoteHelper.narrow(
    super._this_object(orb));
  }


} // class IBanqueRemotePOA
